### 1. Data Types
Python has int, float, string, and boolean types.
They define the type of value a variable can hold.

In [4]:
x = 10
y = 3.14
name = 'Rajat'
is_valid = True
print(x, y, name, is_valid)

10 3.14 Rajat True


### 2. Output & Printing
We use `print()` to display values or messages.
It can handle multiple values at once.

In [5]:
print('Hello,', name)
print('Sum of x and y:', x + y)

Hello, Rajat
Sum of x and y: 13.14


### 3. Variables
Variables store values. They can be reassigned anytime.
Multiple variables can be assigned in one line.

In [10]:
a, b = 5, 7
print('Sum:', a / b)

Sum: 0.7142857142857143


### 4. User Input
`input()` lets users enter values. Always returns a string.
Use `int()` or `float()` for numeric conversion.

In [11]:
# user = input('Enter your name: ')
# print('Welcome,', user)


In [14]:
#Example : # Ask user for multiple inputs
name = input("Enter your name ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")

# Use inputs in logic
if age < 18:
    status = "Minor"
else:
    status = "Adult"

print(f"\nHello {name}! 👋")
print(f"You are {age} years old, living in {city}.")
print(f"Your status: {status}")

Enter your name  rahul
Enter your age:  34
Enter your city:  d.dun



Hello rahul! 👋
You are 34 years old, living in d.dun.
Your status: Adult


### 5. Arithmetic Operators
Python supports +, -, *, /, //, %, and **.
They work on both integers and floats.

In [15]:
print(10 + 3, 10 - 3, 10 * 3, 10 / 3, 10 // 3, 10 % 3, 10 ** 2)

13 7 30 3.3333333333333335 3 1 100


### 6. String Methods
Strings have built-in methods like `upper()`, `title()`, and `replace()`.
They make text processing easier.

In [16]:
msg = 'credit risk modeling'
print(msg.upper(), msg.title(), msg.replace('risk', 'scorecard'))

CREDIT RISK MODELING Credit Risk Modeling credit scorecard modeling


### 7. Conditional Operators
Used to compare values, returning True/False.
Examples: >, <, ==, !=, >=, <=

In [11]:
age = 20
print(age > 18)
print(age == 18, age != 18)


True
False True


### 8. If-Else-Elif
Conditional statements control flow.
Use `if`, `elif`, and `else`.

In [18]:
score = 95
if score >= 90:
    print('Grade: A')
elif score >= 75:
    print('Grade: B')
else:
    print('Grade: C')

Grade: A


In [19]:
#Example
age = 16
student = True
ticket_price = 0

# Check if person is allowed to watch an "A" rated movie
print("Is allowed for A-rated movie?", age >= 18)

# Check if person is exactly 18 years old
print("Is exactly 18?", age == 18)

# Check if person is not 18
print("Is not 18?", age != 18)

# Decide ticket price
if age < 12:
    ticket_price = 100   # kids discount
elif age < 18 and student:
    ticket_price = 150   # student discount
elif age < 18 and student:
    ticket_price = 150
elif age < 18 and student:
    ticket_price = 150
else:
    ticket_price = 250   # normal price

print("Ticket Price:", ticket_price)


Is allowed for A-rated movie? False
Is exactly 18? False
Is not 18? True
Ticket Price: 150


### 9. Lists & Tuples
Lists are mutable, tuples are immutable.
Both store ordered collections.

In [21]:
fruits = ['apple', 'banana', 'cherry']
coords = (10, 20)
print(fruits[1], fruits[-2], coords)

banana banana (10, 20)


### 10. For Loops
`for` loops iterate over items.
Useful for lists, strings, and ranges.

In [22]:
#मान लो आपके पास एक टॉफी का डब्बा है जिसमें 5 टॉफियां रखी हैं।
#आप हर बार एक-एक टॉफी उठाकर खाना चाहते हो।
#डब्बा = list (iterable)
#हर टॉफी = element
#for loop = “हर टॉफी उठाओ और खाओ, जब तक डब्बा खाली न हो जाए”

for fruit in fruits:
    print('Fruit:', fruit)

Fruit: apple
Fruit: banana
Fruit: cherry


### 11. While Loops
`while` loops run until condition is False.
Be careful to avoid infinite loops.

In [24]:
#जब तक कोई condition True है, Python बार-बार वही काम करता रहेगा।
#जैसे ही condition False हुई → loop रुक जाएगा।

n = 3
while n > 0:
    print('Countdown:', n)
    n -= 1

Countdown: 3
Countdown: 2
Countdown: 1


### 12. Slice Operator
Used to extract parts of lists or strings.
Syntax: `[start:end:step]`.

In [25]:
nums = [0, 1, 2, 3, 4, 5]
print(nums[1:4], nums[::-1]) # reverse the list

[1, 2, 3] [5, 4, 3, 2, 1, 0]


### 13. Sets
Sets store unique unordered values.
Automatically removes duplicates.

In [27]:
unique_nums = {1, 5, 2, 2,3,3, 3}
print(unique_nums)

{1, 2, 3, 5}


### 14. Dictionaries
Dictionaries store key-value pairs.
Access values using keys.

In [ ]:
student = {'name': 'Rajat', 'score': 95}
print(student['name'], student.get('score'))

### 15. Comprehensions
Quick way to build collections.
Often used for transformations.
This is called a list comprehension in Python.
👉 It’s a short way to create lists, instead of writing a long loop.

In [28]:
#normal way :
squares = []
for i in range(5):
    squares.append(i**2)

print(squares)


[0, 1, 4, 9, 16]


In [29]:
# LIST COMPREHENSION 
squares = [i**2 for i in range(5)]
print(squares)



[0, 1, 4, 9, 16]


In [22]:
### you comprehend (understand) the entire loop + append logic in one line.
### It’s like writing a full loop inside square brackets [ ]

### 16. Functions
Functions organize reusable code.
Defined using `def`.

In [30]:
def greet(name):
    return f'Hello, {name}!'
print(greet('Rajat'))

Hello, Rajat!


### 17. *args & **kwargs
`*args` handles variable arguments.
`**kwargs` handles keyword arguments.

In [ ]:
# *args (RGS = Regular Arguments / Positional Arguments)
# *args lets you pass multiple values (positional arguments) into a function.
# It collects them into a tuple.

In [31]:
def add_all(*args):
    return sum(args)
print(add_all(1, 2, 3, 4))

def display_info(**kwargs):
    return kwargs
print(display_info(name='Rajat', role='Data Scientist'))

10
{'name': 'Rajat', 'role': 'Data Scientist'}


### 18. Scope & Globals
Local variables exist inside functions.
Use `global` to modify outer variables.

In [37]:
x = 5
def test_scope():
    global x
    x = 10
test_scope()
print('Global x:', x)

Global x: 10


### 19. Exceptions & Handling
Errors can be caught using `try-except`.
Prevents program crashes.

In [38]:
try:
    print(10 / 0)
except ZeroDivisionError:
    print('Error: Division by zero!')

Error: Division by zero!


### 20. Lambda, Map, Filter
Anonymous functions with `lambda`.
Useful with `map()` and `filter()`.

In [39]:
nums = [1, 2, 3, 4, 5]
squared = list(map(lambda n: n**2, nums))    #👉 It applies the given function to each item in the iterable. 
evens = list(filter(lambda n: n % 2 == 0, nums))   #👉 It keeps only those items from the iterable for which the function returns True.
print(nums,squared, evens)

[1, 2, 3, 4, 5] [1, 4, 9, 16, 25] [2, 4]


### 21. F-Strings
F-strings format strings easily.
Variables go inside `{}`.

In [40]:
name, age = 'Rajat', 32
print(f'My name is {name} and I am {age} years old.')

My name is Rajat and I am 32 years old.


### 22. NumPy Arrays & Dimensions
NumPy arrays are efficient containers.
They support vectorized operations.

Faster computations – NumPy arrays are much quicker than Python lists for large datasets.

Memory efficient – They use less memory because all elements are of the same type.

Vectorized operations – You can do element-wise math without loops (e.g., a + b).

Convenient functions – NumPy provides built-in functions for math, statistics, and linear algebra.

Multidimensional support – You can easily work with matrices, images, and higher-dimensional data.

In [43]:
import numpy as np
arr = np.array([1, 2, 3, 4])
mat = np.array([[1, 2], [3, 4]])
print(arr, mat)

type(mat)

[1 2 3 4] [[1 2]
 [3 4]]


numpy.ndarray

In [44]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
])

print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 23. NumPy Indexing & Slicing
Works similar to Python lists.
Also supports multi-dimensional indexing.

In [45]:
print(arr[0], arr[-1], arr[1:3])
print(mat[0, 1], mat[:, 0])

1 4 [2 3]
2 [1 3]


### 24. NumPy Broadcasting
Allows operations on arrays of different shapes.
No need for loops.

In [27]:
arr2 = np.array([10, 20, 30, 40])
print(arr + arr2)

[11 22 33 44]


### 25. NumPy Vectorized Operations
Apply math operations on arrays.
Faster than Python loops.

In [46]:
print(arr * 2, arr ** 2)

[2 4 6 8] [ 1  4  9 16]


### 26. NumPy Statistics
Functions like mean, std, percentile.
Useful for analytics.

In [47]:
print('Mean:', arr.mean(), 'Std:', arr.std(), 'Percentile:', np.percentile(arr2, 50))

NameError: name 'arr2' is not defined

### 27. NumPy Random Sampling
Generate random numbers or arrays.
Useful for ML and testing.

In [50]:
print('Random numbers:', np.random.randint(1, 100, 5))

Random numbers: [70 13 88 29  6]


### 28. Pandas Series & DataFrame
Here are 5 introductory points about Pandas for beginners:

Data Handling Library – Pandas is a Python library used for data manipulation and analysis.

Key Data Structures – Provides Series (1D) and DataFrame (2D table) for storing data efficiently.

Easy Data Cleaning – Helps handle missing data, duplicates, and inconsistent formats easily.

Data Operations – Supports filtering, grouping, merging, and aggregation of data.

Integration with Other Libraries – Works well with NumPy, Matplotlib, and CSV/Excel files for analytics.

Series is 1D, DataFrame is 2D.
Core structures in Pandas.

NOTE :::: NumPy = fast numeric computation, but not designed for labeled, structured, or mixed data. That’s where Pandas comes in.

In [51]:
import pandas as pd

s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s)


data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [85, 90, 95, 80]
}

df = pd.DataFrame(data)
print(df)


a    10
b    20
c    30
dtype: int64
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80


### 29. Pandas Indexing & Selection
Use loc for row selection.
Brackets `[]` for columns.

In [53]:
print(df['Name'])
print(df.loc[0])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
Name     Alice
Age         25
Score       85
Name: 0, dtype: object


### 30. Pandas Filtering
Filter rows based on conditions.
Returns a new DataFrame.

In [36]:
print(df[df['Age'] > 30])

      Name  Age  Score
2  Charlie   35     95
3    David   40     80


### 31. Pandas Handling Missing Values
Fill or drop missing data.
Methods: fillna(), dropna().

In [54]:
df2 = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
print(df2.fillna(0))
print(df2.dropna())

     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0
     A    B
0  1.0  4.0


### 32. Pandas GroupBy & Aggregations
Group rows and compute aggregates.
Like SQL GROUP BY.

In [38]:
print(df.groupby('Age')['Score'].mean())

Age
25    85.0
30    90.0
35    95.0
40    80.0
Name: Score, dtype: float64


### 33. Pandas Merge / Join / Concat
Combine DataFrames like SQL joins.
Merge on keys.

In [55]:
df3 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Dept': ['IT', 'Finance']})
merged = pd.merge(df, df3, on='Name', how='left')
print(merged)

      Name  Age  Score     Dept
0    Alice   25     85       IT
1      Bob   30     90  Finance
2  Charlie   35     95      NaN
3    David   40     80      NaN


### 34. Pandas Apply & Lambda
Apply custom functions to columns.
Row-wise or column-wise.

In [40]:
df['Score2'] = df['Score'].apply(lambda x: x + 5)
print(df)

      Name  Age  Score  Score2
0    Alice   25     85      90
1      Bob   30     90      95
2  Charlie   35     95     100
3    David   40     80      85


### 35. Pandas Feature Engineering
Create new variables from existing ones.
Key in ML.

In [56]:
df['Score_to_Age'] = df['Score'] / df['Age']
print(df)

      Name  Age  Score  Score_to_Age
0    Alice   25     85      3.400000
1      Bob   30     90      3.000000
2  Charlie   35     95      2.714286
3    David   40     80      2.000000


### 36. Pandas Working with Dates
Handles dates and times efficiently.
Supports ranges and operations.

In [57]:
dates = pd.date_range('2025-01-01', periods=5)
df_dates = pd.DataFrame({'Date': dates, 'Value': np.random.randint(1, 100, 5)})
print(df_dates)

        Date  Value
0 2025-01-01     92
1 2025-01-02     93
2 2025-01-03     13
3 2025-01-04     62
4 2025-01-05     97


### 37. Pandas Importing & Exporting Data
Read/write CSV, Excel, SQL, etc.
Use read_csv(), to_csv().

In [1]:
# df.to_csv('students.csv', index=False)
# df_loaded = pd.read_csv('students.csv')
# print(df_loaded)

In [2]:
# ==========================================
# MINIMAL LOGISTIC REGRESSION MODEL - PYTHON
# ==========================================

# 1. Import Libraries
import pandas as pd
from sklearn.linear_model import LogisticRegression

# 2. Create Sample Dataset
data = {
    'Age': [25, 45, 35, 50, 23, 40, 60, 22, 34, 48],
    'Income': [50000, 100000, 75000, 120000, 45000, 90000, 130000, 40000, 70000, 110000],
    'Credit_Score': [600, 700, 650, 720, 580, 690, 740, 590, 660, 710],
    'Default': [0, 0, 0, 0, 1, 0, 0, 1, 0, 0]  # Target variable
}

df = pd.DataFrame(data)

# 3. Define Features and Target
X = df[['Age', 'Income', 'Credit_Score']]
y = df['Default']

# 4. Fit Logistic Regression Model
model = LogisticRegression()
model.fit(X, y)

# 5. Display Model Parameters
print("Intercept:", model.intercept_)
print("Coefficients:")
for feature, coef in zip(X.columns, model.coef_[0]):
    print(f"{feature}: {coef}")

# 6. Make Prediction Example
new_data = pd.DataFrame({
    'Age': [30, 55],
    'Income': [60000, 120000],
    'Credit_Score': [650, 730]
})

pred_class = model.predict(new_data)
pred_prob = model.predict_proba(new_data)

print("\nPredicted Classes:", pred_class)
print("Predicted Probabilities:\n", pred_prob)


Intercept: [0.00049119]
Coefficients:
Age: 0.003004937108594886
Income: -0.0030362124085617868
Credit_Score: 0.2442279643798208

Predicted Classes: [0 0]
Predicted Probabilities:
 [[1.00000000e+00 7.34858409e-11]
 [1.00000000e+00 1.85165573e-81]]
